stages:
  - build
  - test

build-amd64-lin:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq build-essential git cmake
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j4
  tags:
    - linux
    - docker

#build-amd64-win:
#  stage: build
#  script:
#    - mkdir build
#    - cd build
#    - "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin\\cmake.exe .."
#  tags:
#    - windows
#    - shell

test-amd64-lin:
  stage: test
  before_script:
    - apt-get update -qq && apt-get install -y -qq build-essential git cmake
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make ckmm_tests -j4
    - ./ckmm_tests
  artifacts:
    name: tests-linux
    public: false
    expire_in: 1 week
    paths:
      - 'build/ckmm_tests'
  tags:
    - linux
    - docker
