stages:
  - build
  - test

build-amd64:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq build-essential git
  script:
    - make -j4
  tags:
    - linux
    - docker

test-amd64:
  stage: test
  before_script:
    - apt-get update -qq && apt-get install -y -qq build-essential git
  script:
    - make test -j4
    - ./ckmm-test
  tags:
    - linux
    - docker
