stages:
  - build
  - test

build-amd64:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq build-essential git cmake
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make ckmm -j4
  tags:
    - linux
    - docker

test-amd64:
  stage: test
  before_script:
    - apt-get update -qq && apt-get install -y -qq build-essential git cmake
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make ckmm_tests -j4
    - ./ckmm_tests
  tags:
    - linux
    - docker
