#if !defined(__MessageID_H__)
#define __MessageID_H__

enum kmmMessageID {
    CapabilitiesCommand_ID = 0x01,
    CapabilitiesResponse_ID = 0x02,
    ChangeRsiCommand_ID = 0x03,
    ChangeRsiResponse_ID = 0x04,
    ChangeoverCommand_ID = 0x05,
    ChangeoverResponse_ID = 0x06,
    DelayedAcknowledgement_ID = 0x07,
    DeleteKeyCommand_ID = 0x08,
    DeleteKeyResponse_ID = 0x09,
    DeleteKeysetCommand_ID = 0x0A,
    DeleteKeysetResponse_ID = 0x0B,
    Hello_ID = 0x0C,
    InventoryCommand_ID = 0x0D,
    InventoryResponse_ID = 0x0E,
    KeyAssignmentCommand_ID = 0x0F,
    KeyAssignmentResponse_ID = 0x10,
    Reserved11_ID = 0x11,
    Reserved12_ID = 0x12,
    ModifyKeyCommand_ID = 0x13,
    ModifyKeysetAttributesCommand_ID = 0x14,
    ModifyKeysetAttributesResponse_ID = 0x15,
    NegativeAcknowledgment_ID = 0x16,
    NoService_ID = 0x17,
    Reserved18_ID = 0x18,
    Reserved19_ID = 0x19,
    Reserved1A_ID = 0x1A,
    Reserved1B_ID = 0x1B,
    Reserved1C_ID = 0x1C,
    RekeyAcknowledgement_ID = 0x1D,
    RekeyCommand_ID = 0x1E,
    SetDateTime_ID = 0x1F,
    WarmStartCommand_ID = 0x20,
    ZeroizeCommand_ID = 0x21,
    ZeroizeResponse_ID = 0x22,
    DeregistrationCommand_ID = 0x23,
    DeregistrationResponse_ID = 0x24,
    RegistrationCommand_ID = 0x25,
    RegistrationResponse_ID = 0x26,
    UnableToDecryptResponse_ID = 0x27,
    LoadAuthKeyCommand_ID = 0x28,
    LoadAuthKeyResponse_ID = 0x29,
    DeleteAuthKeyCommand_ID = 0x2A,
    DeleteAuthKeyResponse_ID = 0x2B,
    SessionControl_ID = 0x31,
    UnknownMotorolaCommand_ID = 0xA0,
    UnknownMotorolaResponse_ID = 0xA1,
    LoadConfigResponse_ID = 0xFC,
    LoadConfigCommand_ID = 0xFD
};

#endif